// Generated by CoffeeScript 1.3.3
(function() {

  describe('KonamiCode', function() {
    before(function() {
      var element;
      element = document.createElement('div');
      element.id = 'ok';
      element.innerHTML = 'OK';
      element.style.display = 'none';
      document.body.appendChild(element);
      this.element = document.getElementById('ok');
      return add_script('var b = new KonamiCode(\
                function() {\
                    document.getElementById("ok").style.display = "block";\
                }\
            );');
    });
    after(function() {
      return document.body.removeChild(this.element);
    });
    return it('responds to standard konami code', function() {
      expect(this.element.style.display).to.equal('none');
      keydown(38);
      keydown(38);
      keydown(40);
      keydown(40);
      keydown(37);
      keydown(39);
      keydown(37);
      keydown(39);
      keydown(66);
      keydown(65);
      return expect(this.element.style.display).to.equal('block');
    });
  });

}).call(this);
